server:
  port: 1113

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8761/eureka/

spring:
  application:
    name: servcie-account
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;
      filters: stat,wall,log4j2
      initialSize: 5
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 FROM DUAL
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/customer?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    prefer-file-system-access: false
    request-context-attribute: request
    settings:
      number_format: 0.##
    suffix: .html
    template-loader-path: classpath:/templates/
  jpa:
    database: mysql
    format-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: mogao
    show-sql: true
  redis:
#    database: 0.0
    host: 118.89.225.76
    port: 6380
    requirePass: 12345678
#    pool:
#      max-active: 200.0
#      max-idle: 10.0
#      max-wait: -1.0
#      min-idle: 0.0

#    timeout: 1000.0
#   rabbitmq:
#    host: 192.168.60.82
#    password: admin
#    port: 8085
#    username: admin


